-- 擴充 AdminAction enum：新增測驗與作業管理操作類型
-- 此 migration 必須在 non-transactional 模式下執行
-- 因為 ALTER TYPE ... ADD VALUE 在 PostgreSQL < 12 不能在 transaction 中使用

ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'CREATE_QUIZ';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'UPDATE_QUIZ';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'DELETE_QUIZ';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'CREATE_ASSIGNMENT';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'UPDATE_ASSIGNMENT';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'DELETE_ASSIGNMENT';
ALTER TYPE "AdminAction" ADD VALUE IF NOT EXISTS 'REVIEW_ASSIGNMENT';
