ALTER TABLE "Lesson" ADD COLUMN IF NOT EXISTS "subtitleUrl" TEXT;
ALTER TABLE "Lesson" ADD COLUMN IF NOT EXISTS "subtitleLang" TEXT;
ALTER TABLE "Lesson" ADD COLUMN IF NOT EXISTS "subtitleLabel" TEXT;
